Repository revelotech/flutter_formx, pull requests merged in 2023-06, with the labels that each got.

#20 Move files so only the library file is exposed
  CHANGELOG.md
  lib/flutter_formx.dart
  lib/src/form/form_item.dart
  lib/src/form/formx.dart
  lib/src/validator/required_field_validator.dart
  lib/src/validator/validator.dart
  lib/src/validator/validator_result.dart
  test/validator/required_field_validator_test.dart
Labels: enhancement

#21 Rename FormItem to FormXField
  CHANGELOG.md
  README.md
  example/lib/presentation/example_page_view_model.dart
  lib/flutter_formx.dart
  lib/src/form/form_x_field.dart
  lib/src/form/formx.dart
  test/form/form_item_test.dart
  test/form/formx_test.dart
Labels: enhancement, Breaking change

#18 Remove formbuilder references
  .gitignore
  CHANGELOG.md
  README.md
  analysis_options.yaml
  example/analysis_options.yaml
  example/android/app/src/main/kotlin/com/revelo/flutter_formx_example/MainActivity.kt
  example/ios/Runner.xcodeproj/project.pbxproj
  example/lib/presentation/example_page.dart
  example/lib/presentation/example_page_view_model.dart
  lib/flutter_formx.dart
  lib/src/form/form_x_field.dart
  lib/src/form/formx.dart
  lib/src/validator/required_field_validator.dart
  lib/src/validator/validator.dart
  lib/src/validator/validator_result.dart
  test/form/form_item_test.dart
  test/form/formx_test.dart
  test/validator/required_field_validator_test.dart
Labels: documentation

#25 Fix image paths in readme
  CHANGELOG.md
  README.md
Labels: documentation
